name: Master Generator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 3,15 * * *' # Runs at 3:30 AM and 3:30 PM UTC time (8:30 AM and PM IST)

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: Update Latest Instruments + Config Files
      CI_COMMIT_AUTHOR: xcode88
    steps:
    - uses: actions/checkout@v3
    # Build steps
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11.x'
    - run: python --version
    - run: pip install -r requirements.txt
    - run: python master_generator.py

    # Commit and push all changed files.
    - name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
      # Only run on main branch push (e.g. after pull request merge).
      if: contains(fromJson('["schedule", "push", "pull_request"]'), github.event_name)
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "13439842+xcode88@users.noreply.github.com"
        git add --all
        git commit --all -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
